apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vqt0r8428-python 
  janus-idp.io/tekton: vqt0r8428-python
  backstage.io/kubernetes-id: vqt0r8428-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vqt0r8428-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml