apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vqt0r8428-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vqt0r8428-python 
  name: vqt0r8428-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vqt0r8428-python 
